### ISSUE TITLE
Not looing in the right 'place'

### ISSUE THREAD

**Issue by ericbrian** [robheyes/lifxcode#101]
I added the code as descripted in the readme. I then wen to my router and found my lifx bulb at 192.168.86.224. When I go to find devices, I added subnet 192.168.86

But it finds nothing. Also, even though I entered 192.168.86, when I click either 'Discover devices' or 'Discover only new devices,' it shows: subnets [192.168.0] and not 192.168.86.

But, when that failed, I removed that subnet and tried leaving it blank. So, nothing found. 

Yes, both bulbs were on and I also turned one off.

**Comment by robheyes** [comment]
What's the address of your hub? Is it in the 192.168.86 range?

Did you press the Save button after adding the 192.168.86 to the IP Subnets box?

**Comment by ericbrian** [comment]
Yes to both questions. However, it is no longer relevant to me because I threw them away and installed sengled bulbs. Thanks though.
