### ISSUE TITLE
LIFX strip unable to create children

### ISSUE THREAD

**Issue by Mejari** [robheyes/lifxcode#105]
Nothing happens when I attempt to create child devices. This causes null pointers when doing things like setting the strip's level. I've deleted and recreated the device and get the same behavior.

**Comment by robheyes** [comment]
Any errors in the logs when you try to create the child device?

You have added the driver code from LIFXMultizoneChild.groovy I assume.

**Comment by dkilgore90** [comment]
I do see one potential issue - when I added the child devices, I did not add an `uninstalled` method to call `deleteChildDevices` automatically. So it's possible, if you previously removed the device and re-discovered, that you have some phantom/hidden devices.

To check for this, add a `log.warn "${ignored.message}"` at line 85 in the Multizone driver, in the catch IllegalArgumentException clause

**Comment by Mejari** [comment]
I didn't get any additional errors with that extra logging. Logging out the `zoneCount` variable at the beginning of `createChildDevices` returns `null`, so it looks like it's not getting into that loop at all.

**Comment by dkilgore90** [comment]
Can you post a screenshot of the `state` variables for your strip device? Also what firmware version are they running?

It sounds as if the root problem is that it isn't successfully processing any Multizone events from the 1min polling cycle, which is where `state.zoneCount` would get set

**Comment by Mejari** [comment]
Here are the variables

![image](https://user-images.githubusercontent.com/1441727/111947242-490b3500-8a9a-11eb-8bf1-af7c6161f5d6.png)

**Comment by dkilgore90** [comment]
Firmware: 1.22 - so the strips don't support extended Multizone. The app/driver should handle either packet type - are there any errors from either in the scheduled polling each minute?

**Comment by Mejari** [comment]
Looks like another null issue. Here's the logs I get after a few minutes without trying to do anything with the light.

```
dev:2132021-03-24 10:47:59.230 am errorjava.lang.NullPointerException: Cannot get property 'colors' on null object on line 100 (loadLastMultizone)
dev:2132021-03-24 10:46:59.261 am errorjava.lang.NullPointerException: Cannot get property 'colors' on null object on line 100 (loadLastMultizone)
dev:2132021-03-24 10:45:59.402 am errorjava.lang.NullPointerException: Cannot get property 'colors' on null object on line 100 (loadLastMultizone)
dev:2132021-03-24 10:45:48.218 am errorjava.lang.NullPointerException: Cannot get property 'colors' on null object on line 100 (loadLastMultizone)
dev:2132021-03-24 10:45:48.042 am debugSending buffer [36, 0, 0, 52, 68, 76, 69, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 251, 1, 0, 0]
dev:2132021-03-24 10:45:47.971 am debugSending buffer [38, 0, 0, 52, 68, 76, 69, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 246, 1, 0, 0, 0, 7]
dev:2132021-03-24 10:45:47.787 am debugSending buffer [36, 0, 0, 52, 68, 76, 69, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 101, 0, 0, 0]
dev:2132021-03-24 10:45:47.753 am debugSending buffer [36, 0, 0, 52, 68, 76, 69, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0]
dev:2132021-03-24 10:45:47.704 am debugSending buffer [36, 0, 0, 52, 68, 76, 69, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0]
```

**Comment by dkilgore90** [comment]
Ah. This does look like a bug in `loadLastMultizone`, that only impacts devices using the older Multizone packet (not extended MZ).

The first time we poll the device, we won't have any data - so we hit the NPE

**Comment by dkilgore90** [comment]
PR #109 should fix this

**Comment by Mejari** [comment]
Yeah, I was thinking the same thing when I was poking around, but it threw me down a rabbit hole of nulls that made me think the issue is higher up. I tried out your change and that led to

`java.lang.NullPointerException: Cannot invoke method minus() on null object on line 298 (parse)` which I think is saying that `zone_count` is null.

**Comment by dkilgore90** [comment]
Argh - peeling the onion of nulls!

I'll add a fix for this one to the PR.
Sorry about all this trouble, I was testing all of this with my strips that support extended MZ - so all of the data had been discovered once already.

**Comment by Mejari** [comment]
Not a problem, I appreciate the help in diagnosing the issue. Tried it out and that seemed to fix the issue, I can create the child devices now! The first zone seems to be behaving a little oddly, but I'll investigate and file something else later if I need to. Thank you again!
