### ISSUE TITLE
LIFX Clean Implementation

### ISSUE THREAD

**Issue by nelsonmachupa** [robheyes/lifxcode#107]
Hi there! I know the LIFX Clean bulbs are still very, very new, but is there a chance we can at least get a dummy copy of the A19 driver for easy inclusion temporarily? I'm assuming that would be the closest relation.

I can provide any details you may need about the bulb, as I have 2 currently.

Thank you for all your hard work on this, it's changed my home automation life!
https://www.lifx.com/collections/lamps-and-pendants/products/lifx-clean-antibacterial-smart-light

![Screen Shot 2021-03-14 at 2 12 08 PM](https://user-images.githubusercontent.com/28760058/111079195-4d01ea80-84cf-11eb-92e4-f0cae25d84c8.png)

**Comment by robheyes** [comment]
For now, the simplest thing will be to edit the app code for LIFX Master, find the deviceVersion method and add another case to the switch statement for one of the LIFX Color branches e.g.

From:
```
        case 27:
        case 43:
        case 62:
        case 91:
        case 92:
        case 97:
            return [
                    name      : 'LIFX A19',
                    deviceName: 'LIFX Color',
                    features  : [
                            color            : true,
                            infrared         : false,
                            multizone        : false,
                            temperature_range: [min: 2500, max: 9000],
                            chain            : false
                    ]
            ]

```
to
```
        case 27:
        case 43:
        case 62:
        case 91:
        case 92:
        case 97:
        case 99:  // <--- add this line here
            return [
                    name      : 'LIFX A19',
                    deviceName: 'LIFX Color',
                    features  : [
                            color            : true,
                            infrared         : false,
                            multizone        : false,
                            temperature_range: [min: 2500, max: 9000],
                            chain            : false
                    ]
            ]
```

**Comment by nelsonmachupa** [comment]
Thank you for that info! I was able to get that code pasted in (I'm also a programmer by trade) but it's still flagging as null with the same errors as shown in the original screenshot. Below are the two ways I tried pasting it in just to make sure I was understanding where exactly you where pointing to haha. I also cleared the cache before each scan just to make sure.
Let me know if there is anything else specific I should try, maybe a re-install of the whole package then modify & save?

![Screen Shot 2021-03-16 at 12 48 59 AM](https://user-images.githubusercontent.com/28760058/111257439-86cb1200-85f1-11eb-8414-fb872d67845e.png)
![Screen Shot 2021-03-16 at 12 43 59 AM](https://user-images.githubusercontent.com/28760058/111257444-8763a880-85f1-11eb-8186-b709e051bb46.png)

**Comment by dkilgore90** [comment]
Lifx docs also show a bulb type `90` as a "Clean" model - try adding a switch `case 90:` as well.

https://lan.developer.lifx.com/docs/product-registry

**Comment by robheyes** [comment]
I'd missed that one!

**Comment by nelsonmachupa** [comment]
One additional question (/feature request) while I've got your attention:
I'd love to suggest automatic sizing of the IP address space.  Just for us nerdy ones out there!
I'm talking about upgrading the `IP subnet(s): 10.0.0.0` to include `IP subnet(s): 10.0.0.0/20` then it would automatically know for exactly how much it needs to scan. Could also make it easily ignore that `/` when it isn't there so you don't end up with all the support tickets about "what's this /20" and all that haha.

Let me know if I can help ya with that!

But back to the original issue: It worked out beautifully this time!
![Screen Shot 2021-03-16 at 9 35 06 PM](https://user-images.githubusercontent.com/28760058/111401373-92751200-869f-11eb-9c94-fc1d681e80a0.png)

Below is what I updated my code to for anyone looking into this issue as well:
```
        case 27:
        case 43:
        case 62:
        case 91:
        case 92:
        case 97:
            return [
                    name      : 'LIFX A19',
                    deviceName: 'LIFX Color',
                    features  : [
                            color            : true,
                            infrared         : false,
                            multizone        : false,
                            temperature_range: [min: 2500, max: 9000],
                            chain            : false
                    ]
            ]
        case 90:
        case 99:
            return [
                    name      : 'LIFX Clean',
                    deviceName: 'LIFX Color',
                    features  : [
                            color            : true,
                            infrared         : false,
                            multizone        : false,
                            temperature_range: [min: 2500, max: 9000],
                            chain            : false
                    ]
            ]
        case 28:
        case 44:
        case 63:
        case 94:
        case 98:
```
