### ISSUE TITLE
Errors during Discovery 

### ISSUE THREAD

**Issue by wirecutter313** [robheyes/lifxcode#69]
Doing a discovery scan of my network and trying to find all my lifx devices ( I have 7 and 3 have showed up) I've made my scan slow (3600 sec, 20 retries and my local subnet

When I checked the logs I saw this : 

`dev:902019-06-09 08:33:19.333 pm errorjava.lang.NullPointerException: Cannot get property 'commands' on null object on line 158 (parse)
app:342019-06-09 08:33:19.245 pm errororg.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.UQ_DEVICENETWORKID_INDEX_F ON PUBLIC.DEVICE(DEVICE_NETWORK_ID) VALUES 88"; SQL statement:
INSERT INTO DEVICE(VERSION, DEVICE_NETWORK_ID, LABEL, NAME, CONTROLLER_TYPE, ZIGBEE_ID, ENDPOINT_ID, DEVICE_TYPE_ID, LOCATION_ID, HUB_ID, HT_GROUP_ID, PARENT_INSTALLED_APP_ID, PARENT_DEVICE_ID, IS_COMPONENT, DISPLAY_AS_CHILD, CREATE_TIME, LAN_ID) VALUES(1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-199] on line 1199 (discoveryParse)
dev:902019-06-09 08:33:00.449 pm errorjava.lang.NullPointerException: Cannot get property 'commands' on null object on line 158 (parse)
app:342019-06-09 08:33:00.396 pm errororg.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.UQ_DEVICENETWORKID_INDEX_F ON PUBLIC.DEVICE(DEVICE_NETWORK_ID) VALUES 86"; SQL statement:
INSERT INTO DEVICE(VERSION, DEVICE_NETWORK_ID, LABEL, NAME, CONTROLLER_TYPE, ZIGBEE_ID, ENDPOINT_ID, DEVICE_TYPE_ID, LOCATION_ID, HUB_ID, HT_GROUP_ID, PARENT_INSTALLED_APP_ID, PARENT_DEVICE_ID, IS_COMPONENT, DISPLAY_AS_CHILD, CREATE_TIME, LAN_ID) VALUES(1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-199] on line 1199 (discoveryParse)`

**Comment by Dannyzen** [comment]
Same here. Getting 
```2019-08-06 09:42:44.585 pm errorjava.lang.NullPointerException: Cannot invoke method size() on null object on line 106 (discoveryPage)```

**Comment by robheyes** [comment]
Fixed in the current release thanks to @donthorp
