### ISSUE TITLE
Error during discovery

### ISSUE THREAD

**Issue by Dannyzen** [robheyes/lifxcode#72]
Getting ```2019-08-06 09:42:44.585 pm errorjava.lang.NullPointerException: Cannot invoke method size() on null object on line 106 (discoveryPage)``` After discovery attempt

**Comment by robheyes** [comment]
Should be resolved now thanks to donthorp, let me know if it's not.

**Comment by Dannyzen** [comment]
FWIW: This fixed it, thank you!
