### ISSUE TITLE
Error on Saving  "LIFX Discovery"

### ISSUE THREAD

**Issue by TheFlatworm** [robheyes/lifxcode#88]
Importing and saving code into LIFX DISCOVERY creates error: 

Cannot get property 'parent' on null object on line null

Date of import July 7th 2020.  Hubitat version: 2.2.1.116

**Comment by dkilgore90** [comment]
@TheFlatworm The LIFX Discovery Driver is deprecated in the latest code (has been for about a year, IIRC) - this capability was incorporated into the LIFX Master App.

**Comment by TheFlatworm** [comment]
Got it - sorry about the confusion on my part!
