### ISSUE TITLE
Can't install?

### ISSUE THREAD

**Issue by Sugawara9** [robheyes/lifxcode#96]
I just got my Hubitat today.  I tried to install the LIFX code, but after saving, I got this:

No signature of method: Script1.definition() is applicable for argument types: (java.util.LinkedHashMap) values: [[name:LIFX Master, namespace:robheyes, author:Robert Alan Heyes, ...]]

**Comment by dkilgore90** [comment]
Sounds like you pasted the "App" code into a "Driver" - these have different models, attributes, and methods.  The LIFXMasterApp is an App, the rest of the files are Device Drivers for different bulb types.

**Comment by Sugawara9** [comment]
Well now it works! 

I feel silly lol. Thank you! 

----- Original Message -----

**Comment by Sugawara9** [comment]
In the drivers section, I've added the LIFX colour, day and dusk without issues but when I do the Discovery driver and save, I get this error " 
× 
Cannot get property 'parent' on null object" 

----- Original Message -----

**Comment by dkilgore90** [comment]
The Discovery driver is deprecated -- all functionality absorbed into the Master App -- so you no longer need to install this

**Comment by Sugawara9** [comment]
Okay thank you. Sorry, English is my second language. I've noticed that I can discover bulbs. Thanks for your help!

⁣Thanks,
Ross LaVallee​

**Comment by dkilgore90** [comment]
Hey, no worries -- happy to help! If you haven't already, check out the [Hubitat community forum](https://community.hubitat.com/t/lifx-local-control/4023/1) -- lots of tips and tricks there.
